name: CI/CD QA Pipeline

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  qa-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run Cypress tests
        run: npm run cypress:run
        if: steps.install-dependencies.outcome == 'success'

      - name: Run Newman tests
        uses: postmanlabs/action-newman@v2
        with:
          collection: ${{ secrets.POSTMAN_COLLECTION_URL }}
          environment: ${{ secrets.POSTMAN_ENVIRONMENT_URL }}
          environment-variable: API_KEY=${{ secrets.API_KEY }}
        if: steps.run-cypress-tests.outcome == 'success'

      - name: Cleanup
        run: rm -rf node_modules

      - name: Upload Cypress report (if applicable)
        uses: actions/upload-artifact@v3
        with:
          name: cypress-report
          path: cypress/results
        if: always()